language: python
sudo: false

install:
  - pip install -U tox
  - pip install -U codecov

matrix:
  include:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "3.8-dev"
    - python: "3.9-dev"

script:
  - tox -v -e py

after_success:
  - codecov
